language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install --editable . # Install it self
  - pip install -r requirements-test.txt # Install test dependencies
  - pip install codecov # Install coveralls

script:
  - pytest tests --cov=uszipcode # Run unittest

notifications:
  email: false # Mute email notification

after_success:
  - codecov # travis-ci will transfer data to codecov after success